version: "3.7"
services:
  mysql:
    container_name: configurations
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=configurations
    ports:
      - '3306:3306'
    image: 'mysql:5.7'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

#  workflows-api:
#    container_name: workflows-api
#    ports:
#      - '7777:8080'
#    volumes:
#      - '$PWD:/home/wiremock'
#    image: rodolpheche/wiremock

  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes