// Code generated by MockGen. DO NOT EDIT.
// Source: clients/builder.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBuilderClient is a mock of BuilderClient interface
type MockBuilderClient struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderClientMockRecorder
}

// MockBuilderClientMockRecorder is the mock recorder for MockBuilderClient
type MockBuilderClientMockRecorder struct {
	mock *MockBuilderClient
}

// NewMockBuilderClient creates a new mock instance
func NewMockBuilderClient(ctrl *gomock.Controller) *MockBuilderClient {
	mock := &MockBuilderClient{ctrl: ctrl}
	mock.recorder = &MockBuilderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBuilderClient) EXPECT() *MockBuilderClientMockRecorder {
	return m.recorder
}

// CreateJob mocks base method
func (m *MockBuilderClient) CreateJob(config *models.Configuration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJob indicates an expected call of CreateJob
func (mr *MockBuilderClientMockRecorder) CreateJob(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockBuilderClient)(nil).CreateJob), config)
}

// DeleteJob mocks base method
func (m *MockBuilderClient) DeleteJob(config *models.Configuration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob
func (mr *MockBuilderClientMockRecorder) DeleteJob(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockBuilderClient)(nil).DeleteJob), config)
}
